[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
swap = "4nPGmh8cyLjYfDPRRxUKnhLoWaZxDUQAkQ47RhoR2wew"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
# cluster = "devnet"
wallet = "/home/erudyx/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
initialize = "npx ts-node ./scripts/initialize.ts"
init_swap = "npx ts-node ./scripts/init_swap.ts"
init_swap_erc = "npx ts-node ./scripts/init_swap_erc20.ts"
exec_swap = "npx ts-node ./scripts/execute_swap.ts"
exec_swap_erc = "npx ts-node ./scripts/execute_swap_erc20.ts"
mint = "npx ts-node ./scripts/create_and_mint.ts"
